version: '2.3'
services:
  phpbb:
    image: blueimp/phpbb:3.2
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_NAME
      - DBPASSWD
      - PHPBB_INSTALLED
      - AUTO_DB_MIGRATE
    #volumes:
    #  - ./ssl:/etc/apache2/ssl
